steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Python Script
        run: python generate_status.py

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        